/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issues an antiforgery token for the credential endpoints. */
        get: operations["CsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signs in and issues the session cookie. */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revokes the current session and clears the cookie. */
        post: operations["Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the signed-in account, its roles, and its directory placement. */
        get: operations["CurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Changes the caller's own password and revokes their other sessions. */
        post: operations["ChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finds active users by name or email, for a picker. */
        get: operations["SearchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one user's public summary. */
        get: operations["GetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists departments, filtered by search text and optionally including retired ones. */
        get: operations["ListDepartments"];
        put?: never;
        /** Creates a department. */
        post: operations["CreateDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one department. */
        get: operations["GetDepartment"];
        /** Replaces a department's name, code, and description. */
        put: operations["UpdateDepartment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retires a department. Existing references keep resolving. */
        post: operations["DeactivateDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Brings a retired department back into use. */
        post: operations["ReactivateDepartment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists locations in path order, optionally within one parent or one subtree. */
        get: operations["ListLocations"];
        put?: never;
        /** Creates a location under a parent, or a root organisation. */
        post: operations["CreateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one location, including its full path. */
        get: operations["GetLocation"];
        /** Renames a location and rewrites the paths of everything beneath it. */
        put: operations["UpdateLocation"];
        post?: never;
        /** Deletes a location that has no children. A location with children is refused with 409. */
        delete: operations["DeleteLocation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reparents a location, carrying its subtree with it. */
        post: operations["MoveLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists ticket categories in picker order, optionally including retired ones. */
        get: operations["ListTicketCategories"];
        put?: never;
        /** Creates a ticket category. */
        post: operations["CreateTicketCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one ticket category. */
        get: operations["GetTicketCategory"];
        /** Replaces a ticket category's name, description, and order. Existing tickets follow the rename. */
        put: operations["UpdateTicketCategory"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-categories/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retires a ticket category. Existing tickets keep resolving it. */
        post: operations["DeactivateTicketCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-categories/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Brings a retired ticket category back into use. */
        post: operations["ReactivateTicketCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-priorities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists ticket priorities most urgent first, optionally including retired ones. */
        get: operations["ListTicketPriorities"];
        put?: never;
        /** Creates a ticket priority. The code is chosen here and never changes. */
        post: operations["CreateTicketPriority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-priorities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one ticket priority. */
        get: operations["GetTicketPriority"];
        /** Replaces a ticket priority's name, description, order, and SLA targets. The code is immutable. */
        put: operations["UpdateTicketPriority"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-priorities/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retires a ticket priority. Existing tickets keep resolving it. */
        post: operations["DeactivateTicketPriority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ticket-priorities/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Brings a retired ticket priority back into use. */
        post: operations["ReactivateTicketPriority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads a ticket's history, newest first. */
        get: operations["ListTicketHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{id}/status-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moves a ticket to another status, refusing any transition SPEC.md §2 does not allow. */
        post: operations["ChangeTicketStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The account the caller is signed in as. Returned by both `/login` and
         *     `/me`, so the client has one shape to hold for "who am I" however it got there.
         */
        AuthenticatedUserResponse: {
            /**
             * Format: uuid
             * @description The user id.
             */
            id: string;
            /** @description The sign-in name. */
            userName: string;
            /** @description Their address. */
            email: string;
            /** @description The name shown throughout the product. */
            displayName: string;
            /** @description Their roles. The client uses these to hide what a role cannot use; hiding is never the enforcement (ARCHITECTURE.md §7). */
            roles: string[];
            /**
             * Format: uuid
             * @description Their department, if set.
             */
            departmentId: null | string;
            /**
             * Format: uuid
             * @description Their location, if set.
             */
            locationId: null | string;
        };
        /** @description A password change by the account holder. */
        ChangePasswordRequest: {
            /** @description The password in force. Proving possession is what stops a borrowed session changing it. */
            currentPassword: string;
            /** @description The replacement. Checked against the password policy server-side. */
            newPassword: string;
        };
        /** @description The body of `POST /api/v1/tickets/{id}/status-changes`. */
        ChangeTicketStatusRequest: {
            /**
             * @description The status to move to. `Assigned` is not accepted here: a ticket becomes assigned
             *     by assigning it to somebody (WP-1.6), so that the status and the assignee arrive
             *     together. `New` is not accepted either — nothing returns to it.
             */
            status: components["schemas"]["TicketStatus"];
            /**
             * @description What was done. Required and non-blank when Status is
             *     `Resolved`, and rejected for every other destination, because no other transition
             *     records a resolution and silently dropping the text would lose it.
             */
            resolutionNotes: null | string;
        };
        /** @description The body of `POST /api/v1/departments`. */
        CreateDepartmentRequest: {
            /** @description The display name. Unique, case-insensitively. */
            name: string;
            /** @description A short code such as `FIN`, or `null`. Unique when present. */
            code: null | string;
            /** @description Free text, or `null`. */
            description: null | string;
        };
        /** @description The body of `POST /api/v1/locations`. */
        CreateLocationRequest: {
            /** @description The node's own name. Unique among its siblings, case-insensitively. */
            name: string;
            /** @description Which level of the hierarchy it is. */
            kind: components["schemas"]["LocationKind"];
            /**
             * Format: uuid
             * @description The parent node, or `null` to create a root organisation.
             */
            parentId: null | string;
            /** @description Free text, or `null`. */
            description: null | string;
        };
        /** @description The body of `POST /api/v1/ticket-categories`. */
        CreateTicketCategoryRequest: {
            /** @description The display name. Unique, case-insensitively. */
            name: string;
            /** @description What belongs in this category, or `null`. */
            description: null | string;
            /**
             * Format: int32
             * @description Where it sits in a picker. Ties are broken by name.
             */
            sortOrder: number | string;
        };
        /** @description The body of `POST /api/v1/ticket-priorities`. */
        CreateTicketPriorityRequest: {
            /** @description The stable machine identifier, lower-cased on the way in. Unique and immutable. */
            code: string;
            /** @description The display name. Unique, case-insensitively, and editable. */
            name: string;
            /** @description What this priority is for, or `null`. */
            description: null | string;
            /**
             * Format: int32
             * @description Urgency order, lowest first. Ties are broken by name.
             */
            rank: number | string;
            /**
             * Format: int32
             * @description Minutes from creation within which a technician should respond.
             */
            responseTargetMinutes: number | string;
            /**
             * Format: int32
             * @description Minutes from creation within which the ticket should be resolved.
             */
            resolutionTargetMinutes: number | string;
        };
        /** @description The token the browser needs before it may post to a credential endpoint. */
        CsrfTokenResponse: {
            /** @description The request token, sent back in HeaderName. */
            token: string;
            /** @description The header the token belongs in, so the client never hard-codes it. */
            headerName: string;
        };
        /** @description A department as the API renders it. */
        DepartmentResponse: {
            /**
             * Format: uuid
             * @description The department's id.
             */
            id: string;
            /** @description Its display name. */
            name: string;
            /** @description Its short code, or `null`. */
            code: null | string;
            /** @description Free text, or `null`. */
            description: null | string;
            /** @description False once retired. */
            isActive: boolean;
            /**
             * Format: date-time
             * @description When it was created (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When it was last changed (UTC).
             */
            updatedAt: string;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /**
             * Format: int32
             * @description The HTTP status code, repeated in the body as RFC 7807 allows.
             */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
            /** @description The machine-readable error identifier, e.g. auth.antiforgery_failed. Present on every problem this system produces itself; absent on one produced by the framework. */
            code?: string;
        };
        /**
         * @description What a node in the location tree represents. The five levels SPEC.md §5 names:
         *     Organization → Site → Building → Floor/Area → Room.
         * @enum {unknown}
         */
        LocationKind: "Organization" | "Site" | "Building" | "Floor" | "Area" | "Room";
        /** @description A location as the API renders it. */
        LocationResponse: {
            /**
             * Format: uuid
             * @description The node's id.
             */
            id: string;
            /** @description Its own name — "Room G-04", not the whole path. */
            name: string;
            /** @description Which level of the hierarchy it is. */
            kind: components["schemas"]["LocationKind"];
            /**
             * Format: uuid
             * @description Its parent, or `null` at the root.
             */
            parentId: null | string;
            /** @description The full display path from the root, which is what other modules also receive. */
            path: string;
            /**
             * Format: int32
             * @description How far below the root it sits.
             */
            depth: number | string;
            /** @description Free text, or `null`. */
            description: null | string;
            /**
             * Format: int32
             * @description How many nodes sit directly beneath it. Carried so a caller can render the tree and
             *     know whether a delete will be refused before it tries.
             */
            childCount: number | string;
            /**
             * Format: date-time
             * @description When it was created (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When it was last changed (UTC).
             */
            updatedAt: string;
        };
        /** @description Credentials offered at sign-in. */
        LoginRequest: {
            /** @description The sign-in name or the email address; either is accepted. */
            userName: string;
            /** @description The password. Never logged, never echoed, never stored outside its hash. */
            password: string;
        };
        /** @description The body of `POST /api/v1/locations/{id}/move`. */
        MoveLocationRequest: {
            /**
             * Format: uuid
             * @description The new parent, or `null` to move the node to the root — which only
             *     an Organization may be.
             */
            parentId: null | string;
        };
        /**
         * @description The list envelope every paged endpoint returns, fixed by ARCHITECTURE.md §6 as
         *     `{ items, total, page, pageSize }`. It is a type rather than an anonymous
         *     object so the shape reaches OpenAPI and, from there, the generated client.
         */
        PagedResultOfDepartmentResponse: {
            /** @description The items on this page. */
            items: components["schemas"]["DepartmentResponse"][];
            /**
             * Format: int32
             * @description The total number of matching items across all pages.
             */
            total: number | string;
            /**
             * Format: int32
             * @description The 1-based page number this envelope represents.
             */
            page: number | string;
            /**
             * Format: int32
             * @description The page size that was applied, after clamping.
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description The number of pages the current page size yields for int PagedResult&lt;T&gt;.Total items.
             */
            totalPages?: number | string;
            /** @description True when a further page exists. */
            hasNextPage?: boolean;
        };
        /**
         * @description The list envelope every paged endpoint returns, fixed by ARCHITECTURE.md §6 as
         *     `{ items, total, page, pageSize }`. It is a type rather than an anonymous
         *     object so the shape reaches OpenAPI and, from there, the generated client.
         */
        PagedResultOfLocationResponse: {
            /** @description The items on this page. */
            items: components["schemas"]["LocationResponse"][];
            /**
             * Format: int32
             * @description The total number of matching items across all pages.
             */
            total: number | string;
            /**
             * Format: int32
             * @description The 1-based page number this envelope represents.
             */
            page: number | string;
            /**
             * Format: int32
             * @description The page size that was applied, after clamping.
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description The number of pages the current page size yields for int PagedResult&lt;T&gt;.Total items.
             */
            totalPages?: number | string;
            /** @description True when a further page exists. */
            hasNextPage?: boolean;
        };
        /**
         * @description The list envelope every paged endpoint returns, fixed by ARCHITECTURE.md §6 as
         *     `{ items, total, page, pageSize }`. It is a type rather than an anonymous
         *     object so the shape reaches OpenAPI and, from there, the generated client.
         */
        PagedResultOfTicketCategoryResponse: {
            /** @description The items on this page. */
            items: components["schemas"]["TicketCategoryResponse"][];
            /**
             * Format: int32
             * @description The total number of matching items across all pages.
             */
            total: number | string;
            /**
             * Format: int32
             * @description The 1-based page number this envelope represents.
             */
            page: number | string;
            /**
             * Format: int32
             * @description The page size that was applied, after clamping.
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description The number of pages the current page size yields for int PagedResult&lt;T&gt;.Total items.
             */
            totalPages?: number | string;
            /** @description True when a further page exists. */
            hasNextPage?: boolean;
        };
        /**
         * @description The list envelope every paged endpoint returns, fixed by ARCHITECTURE.md §6 as
         *     `{ items, total, page, pageSize }`. It is a type rather than an anonymous
         *     object so the shape reaches OpenAPI and, from there, the generated client.
         */
        PagedResultOfTicketHistoryEntryResponse: {
            /** @description The items on this page. */
            items: components["schemas"]["TicketHistoryEntryResponse"][];
            /**
             * Format: int32
             * @description The total number of matching items across all pages.
             */
            total: number | string;
            /**
             * Format: int32
             * @description The 1-based page number this envelope represents.
             */
            page: number | string;
            /**
             * Format: int32
             * @description The page size that was applied, after clamping.
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description The number of pages the current page size yields for int PagedResult&lt;T&gt;.Total items.
             */
            totalPages?: number | string;
            /** @description True when a further page exists. */
            hasNextPage?: boolean;
        };
        /**
         * @description The list envelope every paged endpoint returns, fixed by ARCHITECTURE.md §6 as
         *     `{ items, total, page, pageSize }`. It is a type rather than an anonymous
         *     object so the shape reaches OpenAPI and, from there, the generated client.
         */
        PagedResultOfTicketPriorityResponse: {
            /** @description The items on this page. */
            items: components["schemas"]["TicketPriorityResponse"][];
            /**
             * Format: int32
             * @description The total number of matching items across all pages.
             */
            total: number | string;
            /**
             * Format: int32
             * @description The 1-based page number this envelope represents.
             */
            page: number | string;
            /**
             * Format: int32
             * @description The page size that was applied, after clamping.
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description The number of pages the current page size yields for int PagedResult&lt;T&gt;.Total items.
             */
            totalPages?: number | string;
            /** @description True when a further page exists. */
            hasNextPage?: boolean;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /**
             * Format: int32
             * @description The HTTP status code, repeated in the body as RFC 7807 allows.
             */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            /** @description The machine-readable error identifier, e.g. auth.antiforgery_failed. Present on every problem this system produces itself; absent on one produced by the framework. */
            code?: string;
            /** @description Per-field validation messages, keyed by camel-cased field name. Present only on a validation failure. */
            errors?: null | {
                [key: string]: string[];
            };
        };
        /** @description A ticket category as the API renders it. */
        TicketCategoryResponse: {
            /**
             * Format: uuid
             * @description The category's id. What a ticket stores, and what a rename does not change.
             */
            id: string;
            /** @description Its display name. */
            name: string;
            /** @description What belongs in it, or `null`. */
            description: null | string;
            /**
             * Format: int32
             * @description Where it sits in a picker.
             */
            sortOrder: number | string;
            /** @description False once retired. */
            isActive: boolean;
            /**
             * Format: date-time
             * @description When it was created (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When it was last changed (UTC).
             */
            updatedAt: string;
        };
        /**
         * @description Which dimension of a ticket a history entry records having moved.
         * @enum {unknown}
         */
        TicketChangeKind: "Status" | "Priority" | "Assignment" | "Resolution";
        /** @description One line of a ticket's timeline, as the API renders it. */
        TicketHistoryEntryResponse: {
            /**
             * Format: uuid
             * @description The entry's id.
             */
            id: string;
            /** @description Which dimension moved. */
            kind: components["schemas"]["TicketChangeKind"];
            /** @description What it read before, or `null` when there was nothing there. */
            fromValue: null | string;
            /** @description What it reads now, or `null` when the change cleared it. */
            toValue: null | string;
            /**
             * Format: date-time
             * @description When the change happened (UTC).
             */
            occurredAt: string;
            /**
             * Format: int32
             * @description Where this line sits among the lines the same change wrote. Entries sharing an
             *     OccurredAt came from one change and are meant to be read together.
             */
            sequence: number | string;
            /**
             * Format: uuid
             * @description Who made it, or `null` when the system did.
             */
            actorId: null | string;
            /** @description Their display name at the time, or `null`. */
            actorName: null | string;
        };
        /** @description A ticket priority as the API renders it. */
        TicketPriorityResponse: {
            /**
             * Format: uuid
             * @description The priority's id. What a ticket stores.
             */
            id: string;
            /** @description The stable machine identifier — `critical`, `high`. Fixed for the life of the row. */
            code: string;
            /** @description Its display name. */
            name: string;
            /** @description What it is for, or `null`. */
            description: null | string;
            /**
             * Format: int32
             * @description Urgency order, lowest first.
             */
            rank: number | string;
            /**
             * Format: int32
             * @description Minutes from creation within which a technician should respond.
             */
            responseTargetMinutes: number | string;
            /**
             * Format: int32
             * @description Minutes from creation within which the ticket should be resolved.
             */
            resolutionTargetMinutes: number | string;
            /** @description False once retired. */
            isActive: boolean;
            /**
             * Format: date-time
             * @description When it was created (UTC).
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When it was last changed (UTC).
             */
            updatedAt: string;
        };
        /**
         * @description Where a ticket sits in the workflow SPEC.md §2 defines.
         * @enum {unknown}
         */
        TicketStatus: "New" | "Assigned" | "InProgress" | "Waiting" | "Resolved" | "Closed" | "Cancelled";
        /** @description What a ticket looks like immediately after a status change. */
        TicketStatusChangeResponse: {
            /**
             * Format: uuid
             * @description The ticket.
             */
            id: string;
            /** @description Its human-readable number, so a toast can name it. */
            number: string;
            /** @description The status it moved from. */
            previousStatus: components["schemas"]["TicketStatus"];
            /** @description The status it is in now. */
            status: components["schemas"]["TicketStatus"];
            /**
             * Format: date-time
             * @description When the move happened, in UTC.
             */
            changedAt: string;
            /**
             * Format: date-time
             * @description When it was resolved, or `null` — cleared by a reopen.
             */
            resolvedAt: null | string;
            /**
             * Format: date-time
             * @description When it was closed, or `null`.
             */
            closedAt: null | string;
            /**
             * @description Where it may go next, straight from the state machine. WP-1.10 must not render a
             *     transition button the server would refuse, and reading it from here is what stops the
             *     table being written a second time in TypeScript. Empty from a terminal state.
             */
            allowedNextStatuses: components["schemas"]["TicketStatus"][];
        };
        /** @description The body of `PUT /api/v1/departments/{id}`. */
        UpdateDepartmentRequest: {
            /** @description The display name. */
            name: string;
            /** @description The short code, or `null` to clear it. */
            code: null | string;
            /** @description Free text, or `null` to clear it. */
            description: null | string;
        };
        /** @description The body of `PUT /api/v1/locations/{id}`. */
        UpdateLocationRequest: {
            /** @description The node's own name. */
            name: string;
            /** @description Free text, or `null` to clear it. */
            description: null | string;
        };
        /** @description The body of `PUT /api/v1/ticket-categories/{id}`. */
        UpdateTicketCategoryRequest: {
            /** @description The display name. Every ticket already filed under this category follows the rename. */
            name: string;
            /** @description What belongs in it, or `null` to clear it. */
            description: null | string;
            /**
             * Format: int32
             * @description Where it sits in a picker.
             */
            sortOrder: number | string;
        };
        /** @description The body of `PUT /api/v1/ticket-priorities/{id}`. */
        UpdateTicketPriorityRequest: {
            /** @description The display name. */
            name: string;
            /** @description What this priority is for, or `null` to clear it. */
            description: null | string;
            /**
             * Format: int32
             * @description Urgency order, lowest first.
             */
            rank: number | string;
            /**
             * Format: int32
             * @description Minutes from creation within which a technician should respond.
             */
            responseTargetMinutes: number | string;
            /**
             * Format: int32
             * @description Minutes from creation within which the ticket should be resolved.
             */
            resolutionTargetMinutes: number | string;
        };
        /**
         * @description The fields another module is allowed to know about a user. It carries no
         *     credential state of any kind — that never leaves Identity.
         */
        UserSummary: {
            /**
             * Format: uuid
             * @description The user's id.
             */
            id: string;
            /** @description The name to show on a ticket, comment, or asset history row. */
            displayName: string;
            /** @description The address notifications go to. */
            email: string;
            /**
             * Format: uuid
             * @description Their department, if set.
             */
            departmentId: null | string;
            /**
             * Format: uuid
             * @description Their location, if set.
             */
            locationId: null | string;
            /** @description False once deactivated. A deactivated user still owns their history (invariant 9). */
            isActive: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SearchUsers: {
        parameters: {
            query?: {
                search?: string;
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListDepartments: {
        parameters: {
            query?: {
                search?: string;
                includeInactive?: boolean;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfDepartmentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDepartmentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeactivateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReactivateDepartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListLocations: {
        parameters: {
            query?: {
                search?: string;
                parentId?: string;
                rootId?: string;
                kind?: components["schemas"]["LocationKind"];
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfLocationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    MoveLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveLocationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListTicketCategories: {
        parameters: {
            query?: {
                includeInactive?: boolean;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfTicketCategoryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateTicketCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketCategoryRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCategoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetTicketCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCategoryResponse"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateTicketCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCategoryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeactivateTicketCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReactivateTicketCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListTicketPriorities: {
        parameters: {
            query?: {
                includeInactive?: boolean;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfTicketPriorityResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateTicketPriority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketPriorityRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPriorityResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetTicketPriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPriorityResponse"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateTicketPriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketPriorityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPriorityResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeactivateTicketPriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReactivateTicketPriority: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session cookie, or the session it named has expired or been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListTicketHistory: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfTicketHistoryEntryResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ChangeTicketStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeTicketStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatusChangeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
