// <auto-generated />
using System;
using System.Net;
using Itms.Modules.Monitoring.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itms.Modules.Monitoring.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    partial class MonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itms.Modules.Monitoring.Domain.CheckResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_check_results");

                    b.HasIndex("DeviceId", "CheckedAt")
                        .HasDatabaseName("ix_check_results_device_id_checked_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DeviceId", "CheckedAt"), "brin");

                    b.ToTable("check_results", "monitoring");
                });

            modelBuilder.Entity("Itms.Modules.Monitoring.Domain.MonitoredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_tag");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("failure_threshold");

                    b.Property<string>("Hostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("MonitoringEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("monitoring_enabled");

                    b.Property<string>("NormalizedHostname")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("normalized_hostname");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("poll_interval_seconds");

                    b.Property<string>("SnmpCommunity")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("snmp_community");

                    b.Property<bool>("SnmpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("snmp_enabled");

                    b.Property<int>("SnmpPort")
                        .HasColumnType("integer")
                        .HasColumnName("snmp_port");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_asset_id");

                    b.HasIndex("NormalizedHostname")
                        .HasDatabaseName("ix_devices_normalized_hostname");

                    b.HasIndex("MonitoringEnabled", "PollIntervalSeconds")
                        .HasDatabaseName("ix_devices_monitoring_enabled_poll_interval");

                    b.ToTable("devices", "monitoring");
                });

            modelBuilder.Entity("Itms.Modules.Monitoring.Domain.CheckResult", b =>
                {
                    b.HasOne("Itms.Modules.Monitoring.Domain.MonitoredDevice", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_check_results_device_id");
                });
#pragma warning restore 612, 618
        }
    }
}
