<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
    <PackageReference Include="Aspire.StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Itms.ServiceDefaults\Itms.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Itms.Platform\Itms.Platform.csproj" />
    <ProjectReference Include="..\Itms.Messaging\Itms.Messaging.csproj" />
    <ProjectReference Include="..\Itms.Contracts\Itms.Contracts.csproj" />
  </ItemGroup>

</Project>
