using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Itms.IntegrationTests.Identity;

namespace Itms.IntegrationTests.Contract;

/// <summary>
/// ARCHITECTURE.md §6 says errors are <c>ProblemDetails</c> <em>always</em>. The mapping
/// itself is unit-tested; this asserts the other half of "always" — the responses no
/// handler produced.
/// </summary>
/// <remarks>
/// Deferred from WP-0.4, which had a database harness and no HTTP one, and recorded in
/// STATUS.md as owed to this package. A 404 from routing and a 401 from the cookie
/// handler are both generated by the framework, and both would be a bare status with an
/// empty body were <c>UseStatusCodePages</c> not wired.
/// </remarks>
[Collection(IdentityTestGroup.Name)]
public sealed class ProblemDetailsResponseTests(IdentityWebFixture fixture)
{
    private const string ProblemJson = "application/problem+json";

    private static CancellationToken Token => TestContext.Current.CancellationToken;

    [Fact]
    public async Task A_route_that_does_not_exist_comes_back_as_a_problem_document()
    {
        using var client = fixture.CreateClient();

        var response = await client.GetAsync(new Uri("/api/v1/no-such-thing", UriKind.Relative), Token);

        response.StatusCode.ShouldBe(HttpStatusCode.NotFound);
        response.Content.Headers.ContentType?.MediaType.ShouldBe(ProblemJson);

        var problem = await ReadProblemAsync(response);
        problem.GetProperty("status").GetInt32().ShouldBe(404);
        problem.TryGetProperty("title", out _).ShouldBeTrue();
    }

    [Fact]
    public async Task An_unauthenticated_call_is_a_problem_document_and_not_a_login_page()
    {
        using var client = fixture.CreateClient();

        var response = await client.GetAsync(new Uri("/api/v1/departments", UriKind.Relative), Token);

        // A redirect to markup is the default an API host has to be configured out of,
        // and it is what would break every fetch in the client (WP-0.5).
        response.StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
        response.Content.Headers.ContentType?.MediaType.ShouldBe(ProblemJson);
    }

    /// <summary>
    /// A handler-produced failure, for contrast with the two above: this one carries the
    /// <c>code</c> extension, which is what the client matches on.
    /// </summary>
    [Fact]
    public async Task A_refused_sign_in_carries_the_machine_readable_code()
    {
        using var client = fixture.CreateClient();

        var response = await AuthClient.LoginAsync(client, "admin", "not-the-password", Token);

        response.StatusCode.ShouldBe(HttpStatusCode.Unauthorized);
        response.Content.Headers.ContentType?.MediaType.ShouldBe(ProblemJson);

        var problem = await ReadProblemAsync(response);
        problem.GetProperty("code").GetString().ShouldNotBeNullOrWhiteSpace();

        // The reason is recorded in the audit trail, never returned to the caller: a
        // response that distinguished "no such account" from "wrong password" would be
        // an enumeration oracle.
        problem.TryGetProperty("reason", out _).ShouldBeFalse();
    }

    /// <summary>
    /// A validation failure, which is the one shape the client maps back onto form fields.
    /// </summary>
    [Fact]
    public async Task A_validation_failure_carries_per_field_errors()
    {
        using var client = fixture.CreateClient();

        // A well-formed request with empty credentials: it reaches the validator rather
        // than being refused as malformed JSON.
        var response = await AuthClient.PostAsync(
            client,
            "/api/v1/auth/login",
            new { userName = "", password = "" },
            Token);

        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
        response.Content.Headers.ContentType?.MediaType.ShouldBe(ProblemJson);

        var problem = await ReadProblemAsync(response);
        problem.GetProperty("code").GetString().ShouldNotBeNullOrWhiteSpace();

        var errors = problem.GetProperty("errors");
        errors.EnumerateObject().ShouldNotBeEmpty();

        // Camel-cased, because the client maps them straight onto form field names
        // (WP-0.3's decision, and what react-hook-form is given).
        errors.EnumerateObject()
            .Select(field => field.Name)
            .ShouldAllBe(name => char.IsLower(name[0]));
    }

    private static async Task<JsonElement> ReadProblemAsync(HttpResponseMessage response) =>
        await response.Content.ReadFromJsonAsync<JsonElement>(TestContext.Current.CancellationToken);
}
